name: Makefile CI

on:
  push:
    branches: [ "main", "novalidation-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    
    - name: Build
      run: arch -x86_64 make CFLAGS="-DTEST_ENV"
    
    - name: Generate token
      run: arch -x86_64 ./token-generator
